-- https://github.com/catppuccin/nvim
local catppuccin = require('catppuccin')

catppuccin.setup({
    dim_inactive = {
        enabled = false,
        shade = "dark",
        percentage = 0.15,
    },
    transparent_background = false,
    term_colors = false,
    compile = {
        enabled = false,
        path = vim.fn.stdpath "cache" .. "/catppuccin",
    },
    styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        loops = {},
        functions = {},
        keywords = {},
        strings = {},
        variables = {},
        numbers = {},
        booleans = {},
        properties = {},
        types = {},
        operators = {},
    },
    integrations = {
        treesitter = true,
        native_lsp = {
            enabled = true,
            virtual_text = {
                errors = { "italic" },
                hints = { "italic" },
                warnings = { "italic" },
                information = { "italic" },
            },
            underlines = {
                errors = { "underline" },
                hints = { "underline" },
                warnings = { "underline" },
                information = { "underline" },
            },
        },
        coc_nvim = false,
        lsp_trouble = true,
        cmp = true,
        lsp_saga = true,
        gitgutter = false,
        gitsigns = true,
        leap = false,
        telescope = true,
        nvimtree = {
            enabled = true,
            show_root = true,
            transparent_panel = false,
        },
        neotree = {
            enabled = false,
            show_root = true,
            transparent_panel = false,
        },
        dap = {
            enabled = false,
            enable_ui = false,
        },
        which_key = false,
        indent_blankline = {
            enabled = true,
            colored_indent_levels = false,
        },
        dashboard = false,
        neogit = false,
        vim_sneak = false,
        fern = false,
        barbar = false,
        bufferline = true,
        markdown = false,
        lightspeed = false,
        ts_rainbow = false,
        hop = false,
        notify = true,
        telekasten = false,
        symbols_outline = false,
        mini = false,
        aerial = false,
        vimwiki = false,
        beacon = false,
    },
    color_overrides = {},
    custom_highlights = {},
})

-- local colors = require('catppuccin.api.colors').get_colors()

-- catppuccin.remap({
--     markdownH1         = { fg = colors.lavender },
--     markdownH2         = { fg = colors.mauve },
--     markdownH3         = { fg = colors.green },
--     markdownH4         = { fg = colors.yellow },
--     markdownH5         = { fg = colors.pink },
--     markdownH6         = { fg = colors.teal },
--     markdownItalic     = { fg = colors.peach, style = 'italic' },
--     markdownBold       = { fg = colors.red, style = 'bold' },
--     markdownBoldItalic = { fg = colors.red, style = 'bold,italic' },
--     markdownCode       = { fg = colors.sapphire },
--     markdownCodeBlock  = { fg = colors.sapphire },
-- })

-- local color_palette = {
--     rosewater = "#F5E0DC",
--     flamingo = "#F2CDCD",
--     pink = "#F5C2E7",
--     mauve = "#CBA6F7",
--     red = "#F38BA8",
--     maroon = "#EBA0AC",
--     peach = "#FAB387",
--     yellow = "#F9E2AF",
--     green = "#A6E3A1",
--     teal = "#94E2D5",
--     sky = "#89DCEB",
--     sapphire = "#74C7EC",
--     blue = "#89B4FA",
--     lavender = "#B4BEFE",

--     text = "#CDD6F4",
--     subtext1 = "#BAC2DE",
--     subtext0 = "#A6ADC8",
--     overlay2 = "#9399B2",
--     overlay1 = "#7F849C",
--     overlay0 = "#6C7086",
--     surface2 = "#585B70",
--     surface1 = "#45475A",
--     surface0 = "#313244",

--     base = "#1E1E2E",
--     mantle = "#181825",
--     crust = "#11111B",
-- }
